version: 2
jobs:
  build:
    docker:
      - image: airdock/oracle-jdk:jdk-8u112
        environment:
          TERM: dumb
          CIRCLE_TEST_REPORTS: /tmp/reports
    steps:
      - run: apt-get update && apt-get install -y ca-certificates git ssh
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}

      - run: ./gradlew --parallel resolveConfigurations

      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches

      - run: ./gradlew generateLock verifyDependencyLocksAreCurrent --stacktrace --parallel
      - run: ./gradlew --parallel build
      - run: ./gradlew testBouncyCastle testSun

      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/ && find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - store_test_results:
          path: /tmp/reports
      #
      # - deploy:
      #     command: |
      #       if [[ "${CIRCLE_BRANCH}" == "develop" || "${CIRCLE_TAG}" =~ [0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)* ]]; then
      #         ./gradlew --stacktrace --continue publish
      #       fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            # CircleCI2 will ignore tags without this. https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
            tags:
              only: /.*/
